// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RainGutter.Api.Data;

#nullable disable

namespace RainGutter.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530044227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RainGutter.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.GutterProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Finish")
                        .HasColumnType("text")
                        .HasColumnName("finish");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<decimal>("PricePerMeter")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_meter");

                    b.Property<int>("SizeInches")
                        .HasColumnType("integer")
                        .HasColumnName("size_inches");

                    b.HasKey("Id")
                        .HasName("pk_gutter_products");

                    b.ToTable("gutter_products", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("ServiceZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("service_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("ServiceZoneId")
                        .HasDatabaseName("ix_leads_service_zone_id");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.PricingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DownspoutPricePerPoint")
                        .HasColumnType("numeric")
                        .HasColumnName("downspout_price_per_point");

                    b.Property<decimal>("HeightSurchargePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("height_surcharge_percent");

                    b.Property<decimal>("MinimumMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("minimum_meters");

                    b.Property<decimal>("RemovalPricePerMeter")
                        .HasColumnType("numeric")
                        .HasColumnName("removal_price_per_meter");

                    b.Property<decimal>("SurveyFee")
                        .HasColumnType("numeric")
                        .HasColumnName("survey_fee");

                    b.HasKey("Id")
                        .HasName("pk_pricing_configs");

                    b.ToTable("pricing_configs", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.QuoteRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DownspoutCount")
                        .HasColumnType("integer")
                        .HasColumnName("downspout_count");

                    b.Property<decimal>("EstimatedTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_total");

                    b.Property<string>("Finish")
                        .HasColumnType("text")
                        .HasColumnName("finish");

                    b.Property<int>("Floors")
                        .HasColumnType("integer")
                        .HasColumnName("floors");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<decimal>("LengthMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("length_meters");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_number");

                    b.Property<bool>("RemoveOld")
                        .HasColumnType("boolean")
                        .HasColumnName("remove_old");

                    b.Property<int>("SizeInches")
                        .HasColumnType("integer")
                        .HasColumnName("size_inches");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_quote_requests");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_quote_requests_lead_id");

                    b.HasIndex("QuoteNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_quote_requests_quote_number");

                    b.ToTable("quote_requests", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.ServiceZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("TravelSurcharge")
                        .HasColumnType("numeric")
                        .HasColumnName("travel_surcharge");

                    b.HasKey("Id")
                        .HasName("pk_service_zones");

                    b.ToTable("service_zones", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.ShopProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("LineOaLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_oa_link");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("QuoteFooterNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_footer_note");

                    b.Property<int>("QuoteValidityDays")
                        .HasColumnType("integer")
                        .HasColumnName("quote_validity_days");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shop_name");

                    b.HasKey("Id")
                        .HasName("pk_shop_profiles");

                    b.ToTable("shop_profiles", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.Lead", b =>
                {
                    b.HasOne("RainGutter.Api.Models.ServiceZone", "ServiceZone")
                        .WithMany()
                        .HasForeignKey("ServiceZoneId")
                        .HasConstraintName("fk_leads_service_zones_service_zone_id");

                    b.Navigation("ServiceZone");
                });

            modelBuilder.Entity("RainGutter.Api.Models.QuoteRequest", b =>
                {
                    b.HasOne("RainGutter.Api.Models.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_requests_leads_lead_id");

                    b.Navigation("Lead");
                });
#pragma warning restore 612, 618
        }
    }
}
