// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RainGutter.Api.Data;

#nullable disable

namespace RainGutter.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604124305_AddNullFilteredJobIndexes")]
    partial class AddNullFilteredJobIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RainGutter.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("SizeInches")
                        .HasColumnType("integer")
                        .HasColumnName("size_inches");

                    b.HasKey("Id")
                        .HasName("pk_building_types");

                    b.ToTable("building_types", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.GutterProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<decimal>("PricePerMeter")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_meter");

                    b.Property<int>("SizeInches")
                        .HasColumnType("integer")
                        .HasColumnName("size_inches");

                    b.HasKey("Id")
                        .HasName("pk_gutter_products");

                    b.ToTable("gutter_products", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer")
                        .HasColumnName("photo_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ApproxLat")
                        .HasColumnType("double precision")
                        .HasColumnName("approx_lat");

                    b.Property<double?>("ApproxLng")
                        .HasColumnType("double precision")
                        .HasColumnName("approx_lng");

                    b.Property<string>("AreaName")
                        .HasColumnType("text")
                        .HasColumnName("area_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DownspoutCount")
                        .HasColumnType("integer")
                        .HasColumnName("downspout_count");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTime?>("InstalledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_date");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<decimal>("LengthMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("length_meters");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<bool>("PhotoConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("photo_consent");

                    b.Property<string>("PublicToken")
                        .HasColumnType("text")
                        .HasColumnName("public_token");

                    b.Property<int?>("QuoteRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("quote_request_id");

                    b.Property<bool>("ShowInPortfolio")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_portfolio");

                    b.Property<int>("SizeInches")
                        .HasColumnType("integer")
                        .HasColumnName("size_inches");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_months");

                    b.Property<string>("WarrantyNumber")
                        .HasColumnType("text")
                        .HasColumnName("warranty_number");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_jobs_import_batch_id");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_public_token")
                        .HasFilter("public_token IS NOT NULL");

                    b.HasIndex("QuoteRequestId")
                        .HasDatabaseName("ix_jobs_quote_request_id");

                    b.HasIndex("WarrantyNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_warranty_number")
                        .HasFilter("warranty_number IS NOT NULL");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.JobPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_job_photos");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_photos_job_id");

                    b.ToTable("job_photos", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("LocationDetail")
                        .HasColumnType("text")
                        .HasColumnName("location_detail");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("ServiceZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("service_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("ServiceZoneId")
                        .HasDatabaseName("ix_leads_service_zone_id");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.PricingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DownspoutPricePerPoint")
                        .HasColumnType("numeric")
                        .HasColumnName("downspout_price_per_point");

                    b.Property<decimal>("HeightSurchargePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("height_surcharge_percent");

                    b.Property<decimal>("MinimumMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("minimum_meters");

                    b.Property<decimal>("RemovalPricePerMeter")
                        .HasColumnType("numeric")
                        .HasColumnName("removal_price_per_meter");

                    b.Property<decimal>("SurveyFee")
                        .HasColumnType("numeric")
                        .HasColumnName("survey_fee");

                    b.HasKey("Id")
                        .HasName("pk_pricing_configs");

                    b.ToTable("pricing_configs", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.QuoteRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<int?>("BuildingTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("building_type_id");

                    b.Property<string>("BuildingTypeLabelSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("building_type_label_snapshot");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DownspoutCount")
                        .HasColumnType("integer")
                        .HasColumnName("downspout_count");

                    b.Property<decimal>("EstimatedTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_total");

                    b.Property<int>("Floors")
                        .HasColumnType("integer")
                        .HasColumnName("floors");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<decimal>("LengthMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("length_meters");

                    b.Property<double?>("MapCenterLat")
                        .HasColumnType("double precision")
                        .HasColumnName("map_center_lat");

                    b.Property<double?>("MapCenterLng")
                        .HasColumnType("double precision")
                        .HasColumnName("map_center_lng");

                    b.Property<int?>("MapZoom")
                        .HasColumnType("integer")
                        .HasColumnName("map_zoom");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<string>("MeasureSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("measure_source");

                    b.Property<string>("MeasuredGeoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("measured_geo_json");

                    b.Property<decimal?>("MeasuredLengthMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("measured_length_meters");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_number");

                    b.Property<bool>("RemoveOld")
                        .HasColumnType("boolean")
                        .HasColumnName("remove_old");

                    b.Property<int>("SizeInches")
                        .HasColumnType("integer")
                        .HasColumnName("size_inches");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_quote_requests");

                    b.HasIndex("BuildingTypeId")
                        .HasDatabaseName("ix_quote_requests_building_type_id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_quote_requests_lead_id");

                    b.HasIndex("QuoteNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_quote_requests_quote_number");

                    b.ToTable("quote_requests", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerNote")
                        .HasColumnType("text")
                        .HasColumnName("customer_note");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_service_requests");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_service_requests_job_id");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.ServiceZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("TravelSurcharge")
                        .HasColumnType("numeric")
                        .HasColumnName("travel_surcharge");

                    b.HasKey("Id")
                        .HasName("pk_service_zones");

                    b.ToTable("service_zones", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.ShopProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("LineOaLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_oa_link");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("QuoteFooterNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_footer_note");

                    b.Property<int>("QuoteValidityDays")
                        .HasColumnType("integer")
                        .HasColumnName("quote_validity_days");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shop_name");

                    b.HasKey("Id")
                        .HasName("pk_shop_profiles");

                    b.ToTable("shop_profiles", (string)null);
                });

            modelBuilder.Entity("RainGutter.Api.Models.Job", b =>
                {
                    b.HasOne("RainGutter.Api.Models.ImportBatch", "ImportBatch")
                        .WithMany("Jobs")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_import_batches_import_batch_id");

                    b.HasOne("RainGutter.Api.Models.QuoteRequest", "QuoteRequest")
                        .WithMany()
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_quote_requests_quote_request_id");

                    b.Navigation("ImportBatch");

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("RainGutter.Api.Models.JobPhoto", b =>
                {
                    b.HasOne("RainGutter.Api.Models.Job", "Job")
                        .WithMany("Photos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_photos_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RainGutter.Api.Models.Lead", b =>
                {
                    b.HasOne("RainGutter.Api.Models.ServiceZone", "ServiceZone")
                        .WithMany()
                        .HasForeignKey("ServiceZoneId")
                        .HasConstraintName("fk_leads_service_zones_service_zone_id");

                    b.Navigation("ServiceZone");
                });

            modelBuilder.Entity("RainGutter.Api.Models.QuoteRequest", b =>
                {
                    b.HasOne("RainGutter.Api.Models.BuildingType", null)
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .HasConstraintName("fk_quote_requests_building_types_building_type_id");

                    b.HasOne("RainGutter.Api.Models.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_requests_leads_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("RainGutter.Api.Models.ServiceRequest", b =>
                {
                    b.HasOne("RainGutter.Api.Models.Job", "Job")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_requests_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RainGutter.Api.Models.ImportBatch", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("RainGutter.Api.Models.Job", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
